### ISSUE TITLE
Duplicate images created for CSS

### ISSUE THREAD

**Issue by codenameone** [shannah/cn1-css#8]
I think I reported this in the past. I'm getting duplicate images when saving CSS specifically this css:

````css
ImageLoader {
    background-image: url(img/logo-login.png);    
    cn1-source-dpi: 480;
}

LoginForm {
    background-image: url(img/background.png);
    cn1-source-dpi: 0;
    cn1-background-type: cn1-image-scaled-fill;
}
````

Produces this resource file (all 4 are multi-image):

<img width="213" alt="screen shot 2018-09-20 at 17 44 03" src="https://user-images.githubusercontent.com/2353641/45826330-fd2a7a00-bcfc-11e8-9391-b651dbeb4e5e.png">
